# docker compose 버전
version: "3.8"  

services:
  # 웹서비스 (django)
  web:
    # . : 현재폴더에 Dockerfile 찾아서 빌드 하겠다.
    build: .
    # 사용 커맨드
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    # 바인딩 볼륨
    volumes:
      - ./:/usr/src/app
    # 환경 설정
    env_file:
      - ./.env.dev
    # db 컨테이너 먼저 실행된 후 실행
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:  # 네임드 볼륨
      - postgres_db:/var/lib/postgresql/data  # 로컬네임드볼륨:컨테이너경로
    env_file:
      - ./.env.postgres.dev
    ports:  # docker 내의 postgres를 보고싶을때
      - "5432:5432"

# 네임드 볼륨 선언
volumes:
  postgres_db: